# Site settings
author: Jharell Chambers
title: 
header-img: img/home-bg.png
email: jharell.chambers@selu.edu
copyright_name: Jharell Chambers
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jhar3ll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
